import './places.dart';

List<Place> popularPlaces = <Place>[
  Place(
    id: 'p-1',
    name: 'New York',
    country: 'USA',
    noOfFlights: 39,
    category: PlaceCategories.Popular,
    totalDistance: '12,530',
    flightTime: '20h 5m',
    image: 'assets/images/newyork.jpg',
  ),
  Place(
    id: 'p-2',
    name: 'Paris',
    country: 'France',
    noOfFlights: 41,
    category: PlaceCategories.Popular,
    totalDistance: '7,005',
    flightTime: '13h 45m',
    image: 'assets/images/paris.jpg',
  ),
  Place(
    id: 'p-3',
    name: 'Amsterdam',
    country: 'Netherlands',
    noOfFlights: 45,
    category: PlaceCategories.Popular,
    totalDistance: '6,849',
    flightTime: '16h 20m',
    image: 'assets/images/amsterdam.jpg',
  ),
  Place(
    id: 'p-4',
    name: 'Agra',
    country: 'India',
    noOfFlights: 33,
    category: PlaceCategories.Popular,
    totalDistance: '1,205',
    flightTime: '1h 15m',
    image: 'assets/images/agra.jpg',
  ),
  Place(
    id: 'p-5',
    name: 'Angakor Wat',
    country: 'Cambodia',
    noOfFlights: 24,
    category: PlaceCategories.Popular,
    totalDistance: '5,590',
    flightTime: '6h 30m',
    image: 'assets/images/angakorwat.jpg',
  ),
  Place(
    id: 'p-6',
    name: 'Colosseum',
    country: 'Rome',
    noOfFlights: 40,
    category: PlaceCategories.Popular,
    totalDistance: '6,171',
    flightTime: '17h 40m',
    image: 'assets/images/colosseum.jpg',
  ),
  Place(
    id: 'p-7',
    name: 'Alberta',
    country: 'Canada',
    noOfFlights: 45,
    category: PlaceCategories.Popular,
    totalDistance: '11,839',
    flightTime: '1d 12h+',
    image: 'assets/images/alberta.jpg',
  ),
];

List<Place> sunandseaPlaces = <Place>[
  Place(
    id: 'p-8',
    name: 'Goa',
    country: 'India',
    noOfFlights: 45,
    category: PlaceCategories.SunSea,
    totalDistance: '586',
    flightTime: '1h 10m',
    image: 'assets/images/goa.jpg',
  ),
  Place(
    id: 'p-9',
    name: 'Hawaii',
    country: 'The United States of America',
    noOfFlights: 20,
    category: PlaceCategories.SunSea,
    totalDistance: '13,175',
    flightTime: '21h 35m+',
    image: 'assets/images/hawaii.jpg',
  ),
  Place(
    id: 'p-10',
    name: 'Maldives',
    country: 'Maldives',
    noOfFlights: 25,
    category: PlaceCategories.SunSea,
    totalDistance: '1764',
    flightTime: '3h 15m',
    image: 'assets/images/maldives.jpg',
  ),
  Place(
    id: 'p-11',
    name: 'Mauritius',
    country: 'Mauritius',
    noOfFlights: 32,
    category: PlaceCategories.SunSea,
    totalDistance: '4688',
    flightTime: '6h+',
    image: 'assets/images/mauritius.jpg',
  ),
];

List<Place> adventurePlaces = <Place>[
  Place(
    id: 'p-11',
    name: 'Mauritius',
    country: 'Mauritius',
    noOfFlights: 32,
    category: PlaceCategories.SunSea,
    totalDistance: '4688',
    flightTime: '6h+',
    image: 'assets/images/mauritius.jpg',
  ),
];
